### PR TITLE
Upgrade Picoquic and fix stream local_error 5

### LINKED ISSUE #105: local_error 5 seen at times with RESET of streams
```
[QCTRL] [QSES] [QUIC] conn_id: 5600765952 data_ctx_id: 5 closing stream stream_id: 46
[QCTRL] [QSES] [QUIC] Reset stream_id: 46 conn_id: 5600765952
[QCTRL] [QSES] [QUIC] Replacing stream using RESET; conn_id: 5600765952 data_ctx_id: 5 existing_stream: 0 write buf drops: 0 tx_queue_discards: 0
[QCTRL] [QSES] [QUIC] conn_id: 5600765952 data_ctx_id: 5 create new stream with stream_id: 58
[QCTRL] [QSES] [QUIC] conn_id: 5600765952 data_ctx_id: 7 closing stream stream_id: 54
[QCTRL] [QSES] [QUIC] Reset stream_id: 54 conn_id: 5600765952
[QCTRL] [QSES] [QUIC] Replacing stream using RESET; conn_id: 5600765952 data_ctx_id: 7 existing_stream: 0 write buf drops: 0 tx_queue_discards: 0
[QCTRL] [QSES] [QUIC] conn_id: 5600765952 data_ctx_id: 7 create new stream with stream_id: 62
[QCTRL] [QSES] [QUIC] conn_id: 5600765952 data_ctx_id: 6 closing stream stream_id: 50
[QCTRL] [QSES] [QUIC] Reset stream_id: 50 conn_id: 5600765952
[QCTRL] [QSES] [QUIC] Replacing stream using RESET; conn_id: 5600765952 data_ctx_id: 6 existing_stream: 0 write buf drops: 0 tx_queue_discards: 0
[QCTRL] [QSES] [QUIC] conn_id: 5600765952 data_ctx_id: 6 create new stream with stream_id: 66
[QCTRL] [QSES] [QUIC] conn_id: 5600765952 stream_id: 58 pri: 6 CB TX delta 419 ms count: 1 tx_queue_size: 12
[QCTRL] [QSES] [QUIC] Closing connection conn_id: 5600765952 stream_id: 0 local_error: 5 remote_error: 0 app_error: 0 remote: 15.197.244.172
[QCTRL] [QSES] [QUIC] Delete data context 0 in conn_id: 5600765952
[QCTRL] [QSES] [QUIC] Delete default context for conn_id: 5600765952, closing connection
[QCTRL] [QSES] connection_status: cid: 5600765952 status: 3
[QCTRL] [QSES] Received disconnect from transport for context: 5600765952
[QCTRL] [QSES] Shutting down context: 5600765952
[QCTRL] [QSES] [QUIC] picoquic ended with 0   
```

### LINKED ISSUE #108: Upgrade picoquic to include connection timeout fix
Submit picoquic issue to see if connection timeout can be added instead of waiting on the fixed 30 second handshake timeout.

### PR DESCRIPTION
**Pull request by TimEvens**
Upgrades picoquic to latest master branch that includes fix for connection timeout.  Fixes stream local error 5 issue. 

* Resolves #108 
* Resolves #105

### CODE REVIEW

File: src/transport_picoquic.cpp [hunk 1]
```diff
@@ -1599,3 +1607,32 @@ void PicoQuicTransport::close_stream(const ConnectionContext& conn_ctx, DataCont
...
+        return;
+    }
+
+    const auto data_ctx_it = conn_it->second.active_data_contexts.find(data_ctx_id);
+    if (data_ctx_it == conn_it->second.active_data_contexts.end()) {
+        return;
+    }
+    
+    picoquic_mark_active_stream(conn_it->second.pq_cnx,
+                                data_ctx_it->second.current_stream_id,1,
```
Comment (paulej) [inline src/transport_picoquic.cpp:1623]: Not a big deal, but that `,1` I almost missed there. I'd suggest putting that on a separate line or at least adding a space.

**Review by paulej — APPROVED** [review]

File: src/transport_picoquic.cpp (hunk 1 above)
Comment (TimEvens) [reply src/transport_picoquic.cpp]: Updated
